// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtbQo89xi7F7NnB68zgek4bzkcEVGnU8',
    appId: '1:223776135071:web:f3e54d164661757a0ecfaa',
    messagingSenderId: '223776135071',
    projectId: 'crud1-6befb',
    authDomain: 'crud1-6befb.firebaseapp.com',
    storageBucket: 'crud1-6befb.appspot.com',
    measurementId: 'G-W1T0RTEM71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5VcaAkZT-bicjAwXPBRLPq8YaQb_lLBI',
    appId: '1:223776135071:android:b934ebb7e5eb19dd0ecfaa',
    messagingSenderId: '223776135071',
    projectId: 'crud1-6befb',
    storageBucket: 'crud1-6befb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6CWcyN9iC-HGDzzpSUFnSpwPvygxcQOE',
    appId: '1:223776135071:ios:6da1bf3bccc12d7d0ecfaa',
    messagingSenderId: '223776135071',
    projectId: 'crud1-6befb',
    storageBucket: 'crud1-6befb.appspot.com',
    iosClientId: '223776135071-11ogm0tvmtmhslvq4ng4ndm88d0s0n07.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6CWcyN9iC-HGDzzpSUFnSpwPvygxcQOE',
    appId: '1:223776135071:ios:6da1bf3bccc12d7d0ecfaa',
    messagingSenderId: '223776135071',
    projectId: 'crud1-6befb',
    storageBucket: 'crud1-6befb.appspot.com',
    iosClientId: '223776135071-11ogm0tvmtmhslvq4ng4ndm88d0s0n07.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud1',
  );
}
